"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0037_qos_limits_min_tres_per import Dbv0037QosLimitsMinTresPer
globals()['Dbv0037QosLimitsMinTresPer'] = Dbv0037QosLimitsMinTresPer
from slurm_rest.model.dbv0037_qos_limits_min_tres import Dbv0037QosLimitsMinTres


class TestDbv0037QosLimitsMinTres(unittest.TestCase):
    """Dbv0037QosLimitsMinTres unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037QosLimitsMinTres(self):
        """Test Dbv0037QosLimitsMinTres"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037QosLimitsMinTres()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
