"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_qos_limits import Dbv0036QosLimits
from slurm_rest.model.dbv0036_qos_preempt import Dbv0036QosPreempt
globals()['Dbv0036QosLimits'] = Dbv0036QosLimits
globals()['Dbv0036QosPreempt'] = Dbv0036QosPreempt
from slurm_rest.model.dbv0036_qos import Dbv0036Qos


class TestDbv0036Qos(unittest.TestCase):
    """Dbv0036Qos unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036Qos(self):
        """Test Dbv0036Qos"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036Qos()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
