"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0037_association_short_info import Dbv0037AssociationShortInfo
globals()['Dbv0037AssociationShortInfo'] = Dbv0037AssociationShortInfo
from slurm_rest.model.dbv0037_user_associations import Dbv0037UserAssociations


class TestDbv0037UserAssociations(unittest.TestCase):
    """Dbv0037UserAssociations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037UserAssociations(self):
        """Test Dbv0037UserAssociations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037UserAssociations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
