"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_error import Dbv0036Error
globals()['Dbv0036Error'] = Dbv0036Error
from slurm_rest.model.dbv0036_account_response import Dbv0036AccountResponse


class TestDbv0036AccountResponse(unittest.TestCase):
    """Dbv0036AccountResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036AccountResponse(self):
        """Test Dbv0036AccountResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036AccountResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
