"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_job_step_step_het import Dbv0036JobStepStepHet
from slurm_rest.model.dbv0036_job_step_step_task import Dbv0036JobStepStepTask
from slurm_rest.model.dbv0036_job_step_step_tres import Dbv0036JobStepStepTres
globals()['Dbv0036JobStepStepHet'] = Dbv0036JobStepStepHet
globals()['Dbv0036JobStepStepTask'] = Dbv0036JobStepStepTask
globals()['Dbv0036JobStepStepTres'] = Dbv0036JobStepStepTres
from slurm_rest.model.dbv0036_job_step_step import Dbv0036JobStepStep


class TestDbv0036JobStepStep(unittest.TestCase):
    """Dbv0036JobStepStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036JobStepStep(self):
        """Test Dbv0036JobStepStep"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036JobStepStep()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
