"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_account import Dbv0036Account
from slurm_rest.model.dbv0036_error import Dbv0036Error
globals()['Dbv0036Account'] = Dbv0036Account
globals()['Dbv0036Error'] = Dbv0036Error
from slurm_rest.model.dbv0036_account_info import Dbv0036AccountInfo


class TestDbv0036AccountInfo(unittest.TestCase):
    """Dbv0036AccountInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036AccountInfo(self):
        """Test Dbv0036AccountInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036AccountInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
