"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0037_error import Dbv0037Error
from slurm_rest.model.dbv0037_job import Dbv0037Job
globals()['Dbv0037Error'] = Dbv0037Error
globals()['Dbv0037Job'] = Dbv0037Job
from slurm_rest.model.dbv0037_job_info import Dbv0037JobInfo


class TestDbv0037JobInfo(unittest.TestCase):
    """Dbv0037JobInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037JobInfo(self):
        """Test Dbv0037JobInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037JobInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
