"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.v0037_partition import V0037Partition


class TestV0037Partition(unittest.TestCase):
    """V0037Partition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0037Partition(self):
        """Test V0037Partition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V0037Partition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
