"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.signal_one_of import SignalOneOf
globals()['SignalOneOf'] = SignalOneOf
from slurm_rest.model.signal import Signal


class TestSignal(unittest.TestCase):
    """Signal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSignal(self):
        """Test Signal"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Signal()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
