"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_diag_time1 import Dbv0036DiagTime1
globals()['Dbv0036DiagTime1'] = Dbv0036DiagTime1
from slurm_rest.model.dbv0036_diag_users import Dbv0036DiagUsers


class TestDbv0036DiagUsers(unittest.TestCase):
    """Dbv0036DiagUsers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036DiagUsers(self):
        """Test Dbv0036DiagUsers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036DiagUsers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
