"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_qos_limits_max_tres_minutes_per import Dbv0036QosLimitsMaxTresMinutesPer
globals()['Dbv0036QosLimitsMaxTresMinutesPer'] = Dbv0036QosLimitsMaxTresMinutesPer
from slurm_rest.model.dbv0036_qos_limits_max_tres_minutes import Dbv0036QosLimitsMaxTresMinutes


class TestDbv0036QosLimitsMaxTresMinutes(unittest.TestCase):
    """Dbv0036QosLimitsMaxTresMinutes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036QosLimitsMaxTresMinutes(self):
        """Test Dbv0036QosLimitsMaxTresMinutes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036QosLimitsMaxTresMinutes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
