"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.job_properties import JobProperties


class TestJobProperties(unittest.TestCase):
    """JobProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobProperties(self):
        """Test JobProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobProperties()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
