"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.v0037_error import V0037Error
from slurm_rest.model.v0037_partition import V0037Partition
globals()['V0037Error'] = V0037Error
globals()['V0037Partition'] = V0037Partition
from slurm_rest.model.v0037_partitions_response import V0037PartitionsResponse


class TestV0037PartitionsResponse(unittest.TestCase):
    """V0037PartitionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0037PartitionsResponse(self):
        """Test V0037PartitionsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V0037PartitionsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
