"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_user_default import Dbv0036UserDefault
from slurm_rest.model.dbv0037_coordinator_info import Dbv0037CoordinatorInfo
from slurm_rest.model.dbv0037_user_associations import Dbv0037UserAssociations
globals()['Dbv0036UserDefault'] = Dbv0036UserDefault
globals()['Dbv0037CoordinatorInfo'] = Dbv0037CoordinatorInfo
globals()['Dbv0037UserAssociations'] = Dbv0037UserAssociations
from slurm_rest.model.dbv0037_user import Dbv0037User


class TestDbv0037User(unittest.TestCase):
    """Dbv0037User unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037User(self):
        """Test Dbv0037User"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037User()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
