"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_association_short_info import Dbv0036AssociationShortInfo
globals()['Dbv0036AssociationShortInfo'] = Dbv0036AssociationShortInfo
from slurm_rest.model.dbv0036_cluster_info_associations import Dbv0036ClusterInfoAssociations


class TestDbv0036ClusterInfoAssociations(unittest.TestCase):
    """Dbv0036ClusterInfoAssociations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036ClusterInfoAssociations(self):
        """Test Dbv0036ClusterInfoAssociations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036ClusterInfoAssociations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
