"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_qos_limits_min_tres_per import Dbv0036QosLimitsMinTresPer
globals()['Dbv0036QosLimitsMinTresPer'] = Dbv0036QosLimitsMinTresPer
from slurm_rest.model.dbv0036_qos_limits_min_tres import Dbv0036QosLimitsMinTres


class TestDbv0036QosLimitsMinTres(unittest.TestCase):
    """Dbv0036QosLimitsMinTres unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036QosLimitsMinTres(self):
        """Test Dbv0036QosLimitsMinTres"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036QosLimitsMinTres()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
