"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.v0036_node_allocation import V0036NodeAllocation


class TestV0036NodeAllocation(unittest.TestCase):
    """V0036NodeAllocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0036NodeAllocation(self):
        """Test V0036NodeAllocation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V0036NodeAllocation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
