"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_job_array_limits import Dbv0036JobArrayLimits
globals()['Dbv0036JobArrayLimits'] = Dbv0036JobArrayLimits
from slurm_rest.model.dbv0036_job_array import Dbv0036JobArray


class TestDbv0036JobArray(unittest.TestCase):
    """Dbv0036JobArray unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036JobArray(self):
        """Test Dbv0036JobArray"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036JobArray()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
