"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.v0036_error import V0036Error
from slurm_rest.model.v0037_diag_statistics import V0037DiagStatistics
globals()['V0036Error'] = V0036Error
globals()['V0037DiagStatistics'] = V0037DiagStatistics
from slurm_rest.model.v0036_diag import V0036Diag


class TestV0036Diag(unittest.TestCase):
    """V0036Diag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0036Diag(self):
        """Test V0036Diag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V0036Diag()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
