"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_job_step_cpu_requested_frequency import Dbv0036JobStepCPURequestedFrequency
globals()['Dbv0036JobStepCPURequestedFrequency'] = Dbv0036JobStepCPURequestedFrequency
from slurm_rest.model.dbv0036_job_step_cpu import Dbv0036JobStepCPU


class TestDbv0036JobStepCPU(unittest.TestCase):
    """Dbv0036JobStepCPU unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036JobStepCPU(self):
        """Test Dbv0036JobStepCPU"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036JobStepCPU()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
