"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_association_max_jobs_per import Dbv0036AssociationMaxJobsPer


class TestDbv0036AssociationMaxJobsPer(unittest.TestCase):
    """Dbv0036AssociationMaxJobsPer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036AssociationMaxJobsPer(self):
        """Test Dbv0036AssociationMaxJobsPer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036AssociationMaxJobsPer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
