"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0037_tres_list import Dbv0037TresList
globals()['Dbv0037TresList'] = Dbv0037TresList
from slurm_rest.model.dbv0037_job_step_step_tres_requested import Dbv0037JobStepStepTresRequested


class TestDbv0037JobStepStepTresRequested(unittest.TestCase):
    """Dbv0037JobStepStepTresRequested unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037JobStepStepTresRequested(self):
        """Test Dbv0037JobStepStepTresRequested"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037JobStepStepTresRequested()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
