"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_qos_limits_max_wall_clock_per import Dbv0036QosLimitsMaxWallClockPer
globals()['Dbv0036QosLimitsMaxWallClockPer'] = Dbv0036QosLimitsMaxWallClockPer
from slurm_rest.model.dbv0036_qos_limits_max_wall_clock import Dbv0036QosLimitsMaxWallClock


class TestDbv0036QosLimitsMaxWallClock(unittest.TestCase):
    """Dbv0036QosLimitsMaxWallClock unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036QosLimitsMaxWallClock(self):
        """Test Dbv0036QosLimitsMaxWallClock"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036QosLimitsMaxWallClock()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
