"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.v0036_job_resources import V0036JobResources
globals()['V0036JobResources'] = V0036JobResources
from slurm_rest.model.v0036_job_response_properties import V0036JobResponseProperties


class TestV0036JobResponseProperties(unittest.TestCase):
    """V0036JobResponseProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0036JobResponseProperties(self):
        """Test V0036JobResponseProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V0036JobResponseProperties()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
