"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_job_exit_code_signal import Dbv0036JobExitCodeSignal
globals()['Dbv0036JobExitCodeSignal'] = Dbv0036JobExitCodeSignal
from slurm_rest.model.dbv0036_job_exit_code import Dbv0036JobExitCode


class TestDbv0036JobExitCode(unittest.TestCase):
    """Dbv0036JobExitCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036JobExitCode(self):
        """Test Dbv0036JobExitCode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036JobExitCode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
