"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.v0037_diag_statistics import V0037DiagStatistics


class TestV0037DiagStatistics(unittest.TestCase):
    """V0037DiagStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0037DiagStatistics(self):
        """Test V0037DiagStatistics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V0037DiagStatistics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
