"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_qos_limits_min_tres import Dbv0036QosLimitsMinTres
globals()['Dbv0036QosLimitsMinTres'] = Dbv0036QosLimitsMinTres
from slurm_rest.model.dbv0036_qos_limits_min import Dbv0036QosLimitsMin


class TestDbv0036QosLimitsMin(unittest.TestCase):
    """Dbv0036QosLimitsMin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036QosLimitsMin(self):
        """Test Dbv0036QosLimitsMin"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036QosLimitsMin()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
