"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.v0037_error import V0037Error
from slurm_rest.model.v0037_reservation import V0037Reservation
globals()['V0037Error'] = V0037Error
globals()['V0037Reservation'] = V0037Reservation
from slurm_rest.model.v0037_reservations_response import V0037ReservationsResponse


class TestV0037ReservationsResponse(unittest.TestCase):
    """V0037ReservationsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0037ReservationsResponse(self):
        """Test V0037ReservationsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V0037ReservationsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
