"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.v0036_signal import V0036Signal


class TestV0036Signal(unittest.TestCase):
    """V0036Signal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0036Signal(self):
        """Test V0036Signal"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V0036Signal()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
