"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_job_array_limits_max import Dbv0036JobArrayLimitsMax
globals()['Dbv0036JobArrayLimitsMax'] = Dbv0036JobArrayLimitsMax
from slurm_rest.model.dbv0036_job_array_limits import Dbv0036JobArrayLimits


class TestDbv0036JobArrayLimits(unittest.TestCase):
    """Dbv0036JobArrayLimits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036JobArrayLimits(self):
        """Test Dbv0036JobArrayLimits"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036JobArrayLimits()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
