"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_coordinator_info import Dbv0036CoordinatorInfo
from slurm_rest.model.dbv0036_user_associations import Dbv0036UserAssociations
from slurm_rest.model.dbv0036_user_default import Dbv0036UserDefault
globals()['Dbv0036CoordinatorInfo'] = Dbv0036CoordinatorInfo
globals()['Dbv0036UserAssociations'] = Dbv0036UserAssociations
globals()['Dbv0036UserDefault'] = Dbv0036UserDefault
from slurm_rest.model.dbv0036_user import Dbv0036User


class TestDbv0036User(unittest.TestCase):
    """Dbv0036User unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036User(self):
        """Test Dbv0036User"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036User()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
