"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_job_array_limits_max_running import Dbv0036JobArrayLimitsMaxRunning
globals()['Dbv0036JobArrayLimitsMaxRunning'] = Dbv0036JobArrayLimitsMaxRunning
from slurm_rest.model.dbv0036_job_array_limits_max import Dbv0036JobArrayLimitsMax


class TestDbv0036JobArrayLimitsMax(unittest.TestCase):
    """Dbv0036JobArrayLimitsMax unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036JobArrayLimitsMax(self):
        """Test Dbv0036JobArrayLimitsMax"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036JobArrayLimitsMax()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
