"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_tres_list import Dbv0036TresList
globals()['Dbv0036TresList'] = Dbv0036TresList
from slurm_rest.model.dbv0036_job_tres import Dbv0036JobTres


class TestDbv0036JobTres(unittest.TestCase):
    """Dbv0036JobTres unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036JobTres(self):
        """Test Dbv0036JobTres"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036JobTres()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
