"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.v0037_diag_statistics import V0037DiagStatistics
from slurm_rest.model.v0037_error import V0037Error
globals()['V0037DiagStatistics'] = V0037DiagStatistics
globals()['V0037Error'] = V0037Error
from slurm_rest.model.v0037_diag import V0037Diag


class TestV0037Diag(unittest.TestCase):
    """V0037Diag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0037Diag(self):
        """Test V0037Diag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V0037Diag()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
