"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0037_account import Dbv0037Account
from slurm_rest.model.dbv0037_association import Dbv0037Association
from slurm_rest.model.dbv0037_error import Dbv0037Error
from slurm_rest.model.dbv0037_qos import Dbv0037Qos
from slurm_rest.model.dbv0037_tres_list import Dbv0037TresList
from slurm_rest.model.dbv0037_user import Dbv0037User
from slurm_rest.model.dbv0037_wckey import Dbv0037Wckey
globals()['Dbv0037Account'] = Dbv0037Account
globals()['Dbv0037Association'] = Dbv0037Association
globals()['Dbv0037Error'] = Dbv0037Error
globals()['Dbv0037Qos'] = Dbv0037Qos
globals()['Dbv0037TresList'] = Dbv0037TresList
globals()['Dbv0037User'] = Dbv0037User
globals()['Dbv0037Wckey'] = Dbv0037Wckey
from slurm_rest.model.dbv0037_config_info import Dbv0037ConfigInfo


class TestDbv0037ConfigInfo(unittest.TestCase):
    """Dbv0037ConfigInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037ConfigInfo(self):
        """Test Dbv0037ConfigInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037ConfigInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
