"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_error import Dbv0036Error
globals()['Dbv0036Error'] = Dbv0036Error
from slurm_rest.model.dbv0036_response_wckey_add import Dbv0036ResponseWckeyAdd


class TestDbv0036ResponseWckeyAdd(unittest.TestCase):
    """Dbv0036ResponseWckeyAdd unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036ResponseWckeyAdd(self):
        """Test Dbv0036ResponseWckeyAdd"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036ResponseWckeyAdd()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
