"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0037_error import Dbv0037Error
globals()['Dbv0037Error'] = Dbv0037Error
from slurm_rest.model.dbv0037_response_cluster_add import Dbv0037ResponseClusterAdd


class TestDbv0037ResponseClusterAdd(unittest.TestCase):
    """Dbv0037ResponseClusterAdd unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037ResponseClusterAdd(self):
        """Test Dbv0037ResponseClusterAdd"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037ResponseClusterAdd()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
