"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_qos_limits_max_wall_clock_per import Dbv0036QosLimitsMaxWallClockPer


class TestDbv0036QosLimitsMaxWallClockPer(unittest.TestCase):
    """Dbv0036QosLimitsMaxWallClockPer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036QosLimitsMaxWallClockPer(self):
        """Test Dbv0036QosLimitsMaxWallClockPer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036QosLimitsMaxWallClockPer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
