"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0037_qos_limits_max_tres_minutes_per import Dbv0037QosLimitsMaxTresMinutesPer
globals()['Dbv0037QosLimitsMaxTresMinutesPer'] = Dbv0037QosLimitsMaxTresMinutesPer
from slurm_rest.model.dbv0037_qos_limits_max_tres_minutes import Dbv0037QosLimitsMaxTresMinutes


class TestDbv0037QosLimitsMaxTresMinutes(unittest.TestCase):
    """Dbv0037QosLimitsMaxTresMinutes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037QosLimitsMaxTresMinutes(self):
        """Test Dbv0037QosLimitsMaxTresMinutes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037QosLimitsMaxTresMinutes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
