"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_association_default import Dbv0036AssociationDefault
from slurm_rest.model.dbv0036_association_min import Dbv0036AssociationMin
from slurm_rest.model.dbv0036_association_usage import Dbv0036AssociationUsage
from slurm_rest.model.dbv0037_association_max import Dbv0037AssociationMax
globals()['Dbv0036AssociationDefault'] = Dbv0036AssociationDefault
globals()['Dbv0036AssociationMin'] = Dbv0036AssociationMin
globals()['Dbv0036AssociationUsage'] = Dbv0036AssociationUsage
globals()['Dbv0037AssociationMax'] = Dbv0037AssociationMax
from slurm_rest.model.dbv0037_association import Dbv0037Association


class TestDbv0037Association(unittest.TestCase):
    """Dbv0037Association unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037Association(self):
        """Test Dbv0037Association"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037Association()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
