"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import slurm_rest
from slurm_rest.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_slurm_v0035_diag_get(self):
        """Test case for slurm_v0035_diag_get

        get diagnostics  # noqa: E501
        """
        pass

    def test_slurm_v0035_job_job_id_delete(self):
        """Test case for slurm_v0035_job_job_id_delete

        cancel or signal job  # noqa: E501
        """
        pass

    def test_slurm_v0035_job_job_id_get(self):
        """Test case for slurm_v0035_job_job_id_get

        get job info  # noqa: E501
        """
        pass

    def test_slurm_v0035_job_job_id_post(self):
        """Test case for slurm_v0035_job_job_id_post

        update job  # noqa: E501
        """
        pass

    def test_slurm_v0035_job_submit_post(self):
        """Test case for slurm_v0035_job_submit_post

        submit new job  # noqa: E501
        """
        pass

    def test_slurm_v0035_jobs_get(self):
        """Test case for slurm_v0035_jobs_get

        get list of jobs  # noqa: E501
        """
        pass

    def test_slurm_v0035_node_node_name_get(self):
        """Test case for slurm_v0035_node_node_name_get

        get node info  # noqa: E501
        """
        pass

    def test_slurm_v0035_nodes_get(self):
        """Test case for slurm_v0035_nodes_get

        get all node info  # noqa: E501
        """
        pass

    def test_slurm_v0035_partition_partition_name_get(self):
        """Test case for slurm_v0035_partition_partition_name_get

        get partition info  # noqa: E501
        """
        pass

    def test_slurm_v0035_partitions_get(self):
        """Test case for slurm_v0035_partitions_get

        get all partition info  # noqa: E501
        """
        pass

    def test_slurm_v0035_ping_get(self):
        """Test case for slurm_v0035_ping_get

        ping test  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
