"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_association_default import Dbv0036AssociationDefault
from slurm_rest.model.dbv0036_association_max import Dbv0036AssociationMax
from slurm_rest.model.dbv0036_association_min import Dbv0036AssociationMin
from slurm_rest.model.dbv0036_association_usage import Dbv0036AssociationUsage
globals()['Dbv0036AssociationDefault'] = Dbv0036AssociationDefault
globals()['Dbv0036AssociationMax'] = Dbv0036AssociationMax
globals()['Dbv0036AssociationMin'] = Dbv0036AssociationMin
globals()['Dbv0036AssociationUsage'] = Dbv0036AssociationUsage
from slurm_rest.model.dbv0036_association import Dbv0036Association


class TestDbv0036Association(unittest.TestCase):
    """Dbv0036Association unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036Association(self):
        """Test Dbv0036Association"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036Association()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
