"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_job_time_system import Dbv0036JobTimeSystem
from slurm_rest.model.dbv0036_job_time_total import Dbv0036JobTimeTotal
from slurm_rest.model.dbv0036_job_time_user import Dbv0036JobTimeUser
globals()['Dbv0036JobTimeSystem'] = Dbv0036JobTimeSystem
globals()['Dbv0036JobTimeTotal'] = Dbv0036JobTimeTotal
globals()['Dbv0036JobTimeUser'] = Dbv0036JobTimeUser
from slurm_rest.model.dbv0036_job_step_time import Dbv0036JobStepTime


class TestDbv0036JobStepTime(unittest.TestCase):
    """Dbv0036JobStepTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036JobStepTime(self):
        """Test Dbv0036JobStepTime"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036JobStepTime()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
