"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_error import Dbv0036Error
from slurm_rest.model.dbv0036_user import Dbv0036User
globals()['Dbv0036Error'] = Dbv0036Error
globals()['Dbv0036User'] = Dbv0036User
from slurm_rest.model.dbv0036_user_info import Dbv0036UserInfo


class TestDbv0036UserInfo(unittest.TestCase):
    """Dbv0036UserInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036UserInfo(self):
        """Test Dbv0036UserInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036UserInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
