"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_job_array import Dbv0036JobArray
from slurm_rest.model.dbv0036_job_comment import Dbv0036JobComment
from slurm_rest.model.dbv0036_job_het import Dbv0036JobHet
from slurm_rest.model.dbv0036_job_mcs import Dbv0036JobMcs
from slurm_rest.model.dbv0036_job_required import Dbv0036JobRequired
from slurm_rest.model.dbv0036_job_reservation import Dbv0036JobReservation
from slurm_rest.model.dbv0036_job_time import Dbv0036JobTime
from slurm_rest.model.dbv0036_job_wckey import Dbv0036JobWckey
from slurm_rest.model.dbv0037_association_short_info import Dbv0037AssociationShortInfo
from slurm_rest.model.dbv0037_job_exit_code import Dbv0037JobExitCode
from slurm_rest.model.dbv0037_job_state import Dbv0037JobState
from slurm_rest.model.dbv0037_job_step import Dbv0037JobStep
from slurm_rest.model.dbv0037_job_tres import Dbv0037JobTres
globals()['Dbv0036JobArray'] = Dbv0036JobArray
globals()['Dbv0036JobComment'] = Dbv0036JobComment
globals()['Dbv0036JobHet'] = Dbv0036JobHet
globals()['Dbv0036JobMcs'] = Dbv0036JobMcs
globals()['Dbv0036JobRequired'] = Dbv0036JobRequired
globals()['Dbv0036JobReservation'] = Dbv0036JobReservation
globals()['Dbv0036JobTime'] = Dbv0036JobTime
globals()['Dbv0036JobWckey'] = Dbv0036JobWckey
globals()['Dbv0037AssociationShortInfo'] = Dbv0037AssociationShortInfo
globals()['Dbv0037JobExitCode'] = Dbv0037JobExitCode
globals()['Dbv0037JobState'] = Dbv0037JobState
globals()['Dbv0037JobStep'] = Dbv0037JobStep
globals()['Dbv0037JobTres'] = Dbv0037JobTres
from slurm_rest.model.dbv0037_job import Dbv0037Job


class TestDbv0037Job(unittest.TestCase):
    """Dbv0037Job unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037Job(self):
        """Test Dbv0037Job"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037Job()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
