"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_qos_limits_max_accruing_per import Dbv0036QosLimitsMaxAccruingPer
globals()['Dbv0036QosLimitsMaxAccruingPer'] = Dbv0036QosLimitsMaxAccruingPer
from slurm_rest.model.dbv0036_qos_limits_max_accruing import Dbv0036QosLimitsMaxAccruing


class TestDbv0036QosLimitsMaxAccruing(unittest.TestCase):
    """Dbv0036QosLimitsMaxAccruing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036QosLimitsMaxAccruing(self):
        """Test Dbv0036QosLimitsMaxAccruing"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036QosLimitsMaxAccruing()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
