"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_qos_limits_max_tres_minutes import Dbv0036QosLimitsMaxTresMinutes
from slurm_rest.model.dbv0036_qos_limits_max_tres_per import Dbv0036QosLimitsMaxTresPer
globals()['Dbv0036QosLimitsMaxTresMinutes'] = Dbv0036QosLimitsMaxTresMinutes
globals()['Dbv0036QosLimitsMaxTresPer'] = Dbv0036QosLimitsMaxTresPer
from slurm_rest.model.dbv0036_qos_limits_max_tres import Dbv0036QosLimitsMaxTres


class TestDbv0036QosLimitsMaxTres(unittest.TestCase):
    """Dbv0036QosLimitsMaxTres unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036QosLimitsMaxTres(self):
        """Test Dbv0036QosLimitsMaxTres"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036QosLimitsMaxTres()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
