"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0037_job_state import Dbv0037JobState


class TestDbv0037JobState(unittest.TestCase):
    """Dbv0037JobState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037JobState(self):
        """Test Dbv0037JobState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037JobState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
