"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_job_exit_code import Dbv0036JobExitCode
from slurm_rest.model.dbv0036_job_step_cpu import Dbv0036JobStepCPU
from slurm_rest.model.dbv0036_job_step_nodes import Dbv0036JobStepNodes
from slurm_rest.model.dbv0036_job_step_statistics import Dbv0036JobStepStatistics
from slurm_rest.model.dbv0036_job_step_step import Dbv0036JobStepStep
from slurm_rest.model.dbv0036_job_step_tasks import Dbv0036JobStepTasks
from slurm_rest.model.dbv0036_job_step_time import Dbv0036JobStepTime
globals()['Dbv0036JobExitCode'] = Dbv0036JobExitCode
globals()['Dbv0036JobStepCPU'] = Dbv0036JobStepCPU
globals()['Dbv0036JobStepNodes'] = Dbv0036JobStepNodes
globals()['Dbv0036JobStepStatistics'] = Dbv0036JobStepStatistics
globals()['Dbv0036JobStepStep'] = Dbv0036JobStepStep
globals()['Dbv0036JobStepTasks'] = Dbv0036JobStepTasks
globals()['Dbv0036JobStepTime'] = Dbv0036JobStepTime
from slurm_rest.model.dbv0036_job_step import Dbv0036JobStep


class TestDbv0036JobStep(unittest.TestCase):
    """Dbv0036JobStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036JobStep(self):
        """Test Dbv0036JobStep"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036JobStep()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
