"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.v0036_job_properties import V0036JobProperties
globals()['V0036JobProperties'] = V0036JobProperties
from slurm_rest.model.v0036_job_submission import V0036JobSubmission


class TestV0036JobSubmission(unittest.TestCase):
    """V0036JobSubmission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0036JobSubmission(self):
        """Test V0036JobSubmission"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V0036JobSubmission()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
