"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_association_max_per_account import Dbv0036AssociationMaxPerAccount
globals()['Dbv0036AssociationMaxPerAccount'] = Dbv0036AssociationMaxPerAccount
from slurm_rest.model.dbv0036_association_max_per import Dbv0036AssociationMaxPer


class TestDbv0036AssociationMaxPer(unittest.TestCase):
    """Dbv0036AssociationMaxPer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036AssociationMaxPer(self):
        """Test Dbv0036AssociationMaxPer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036AssociationMaxPer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
