"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.v0036_error import V0036Error
from slurm_rest.model.v0036_node import V0036Node
globals()['V0036Error'] = V0036Error
globals()['V0036Node'] = V0036Node
from slurm_rest.model.v0036_nodes_response import V0036NodesResponse


class TestV0036NodesResponse(unittest.TestCase):
    """V0036NodesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0036NodesResponse(self):
        """Test V0036NodesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V0036NodesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
