"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_qos_preempt import Dbv0036QosPreempt
from slurm_rest.model.dbv0037_qos_limits import Dbv0037QosLimits
globals()['Dbv0036QosPreempt'] = Dbv0036QosPreempt
globals()['Dbv0037QosLimits'] = Dbv0037QosLimits
from slurm_rest.model.dbv0037_qos import Dbv0037Qos


class TestDbv0037Qos(unittest.TestCase):
    """Dbv0037Qos unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037Qos(self):
        """Test Dbv0037Qos"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037Qos()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
