"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_diag_rollups import Dbv0036DiagRollups
from slurm_rest.model.dbv0036_diag_rpcs import Dbv0036DiagRPCs
from slurm_rest.model.dbv0036_diag_users import Dbv0036DiagUsers
from slurm_rest.model.dbv0036_error import Dbv0036Error
globals()['Dbv0036DiagRPCs'] = Dbv0036DiagRPCs
globals()['Dbv0036DiagRollups'] = Dbv0036DiagRollups
globals()['Dbv0036DiagUsers'] = Dbv0036DiagUsers
globals()['Dbv0036Error'] = Dbv0036Error
from slurm_rest.model.dbv0036_diag import Dbv0036Diag


class TestDbv0036Diag(unittest.TestCase):
    """Dbv0036Diag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036Diag(self):
        """Test Dbv0036Diag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036Diag()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
