"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_qos_limits_max import Dbv0036QosLimitsMax
from slurm_rest.model.dbv0036_qos_limits_min import Dbv0036QosLimitsMin
globals()['Dbv0036QosLimitsMax'] = Dbv0036QosLimitsMax
globals()['Dbv0036QosLimitsMin'] = Dbv0036QosLimitsMin
from slurm_rest.model.dbv0036_qos_limits import Dbv0036QosLimits


class TestDbv0036QosLimits(unittest.TestCase):
    """Dbv0036QosLimits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036QosLimits(self):
        """Test Dbv0036QosLimits"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036QosLimits()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
