"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.v0036_ping import V0036Ping


class TestV0036Ping(unittest.TestCase):
    """V0036Ping unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0036Ping(self):
        """Test V0036Ping"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V0036Ping()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
