"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0037_tres_list import Dbv0037TresList


class TestDbv0037TresList(unittest.TestCase):
    """Dbv0037TresList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037TresList(self):
        """Test Dbv0037TresList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037TresList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
