"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0037_account import Dbv0037Account
from slurm_rest.model.dbv0037_error import Dbv0037Error
globals()['Dbv0037Account'] = Dbv0037Account
globals()['Dbv0037Error'] = Dbv0037Error
from slurm_rest.model.dbv0037_account_info import Dbv0037AccountInfo


class TestDbv0037AccountInfo(unittest.TestCase):
    """Dbv0037AccountInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037AccountInfo(self):
        """Test Dbv0037AccountInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037AccountInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
