"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.v0037_job_resources import V0037JobResources
globals()['V0037JobResources'] = V0037JobResources
from slurm_rest.model.v0037_job_response_properties import V0037JobResponseProperties


class TestV0037JobResponseProperties(unittest.TestCase):
    """V0037JobResponseProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0037JobResponseProperties(self):
        """Test V0037JobResponseProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V0037JobResponseProperties()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
