"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.v0037_error import V0037Error
from slurm_rest.model.v0037_ping import V0037Ping
globals()['V0037Error'] = V0037Error
globals()['V0037Ping'] = V0037Ping
from slurm_rest.model.v0037_pings import V0037Pings


class TestV0037Pings(unittest.TestCase):
    """V0037Pings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0037Pings(self):
        """Test V0037Pings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V0037Pings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
