"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0037_qos_limits_min_tres import Dbv0037QosLimitsMinTres
globals()['Dbv0037QosLimitsMinTres'] = Dbv0037QosLimitsMinTres
from slurm_rest.model.dbv0037_qos_limits_min import Dbv0037QosLimitsMin


class TestDbv0037QosLimitsMin(unittest.TestCase):
    """Dbv0037QosLimitsMin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037QosLimitsMin(self):
        """Test Dbv0037QosLimitsMin"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037QosLimitsMin()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
