"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_error import Dbv0036Error
from slurm_rest.model.dbv0036_wckey import Dbv0036Wckey
globals()['Dbv0036Error'] = Dbv0036Error
globals()['Dbv0036Wckey'] = Dbv0036Wckey
from slurm_rest.model.dbv0036_wckey_info import Dbv0036WckeyInfo


class TestDbv0036WckeyInfo(unittest.TestCase):
    """Dbv0036WckeyInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036WckeyInfo(self):
        """Test Dbv0036WckeyInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036WckeyInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
