"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.v0037_error import V0037Error
from slurm_rest.model.v0037_job_response_properties import V0037JobResponseProperties
globals()['V0037Error'] = V0037Error
globals()['V0037JobResponseProperties'] = V0037JobResponseProperties
from slurm_rest.model.v0037_jobs_response import V0037JobsResponse


class TestV0037JobsResponse(unittest.TestCase):
    """V0037JobsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0037JobsResponse(self):
        """Test V0037JobsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V0037JobsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
