"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.v0036_error import V0036Error
from slurm_rest.model.v0036_partition import V0036Partition
globals()['V0036Error'] = V0036Error
globals()['V0036Partition'] = V0036Partition
from slurm_rest.model.v0036_partitions_response import V0036PartitionsResponse


class TestV0036PartitionsResponse(unittest.TestCase):
    """V0036PartitionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0036PartitionsResponse(self):
        """Test V0036PartitionsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V0036PartitionsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
