"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_cluster_info_controller import Dbv0036ClusterInfoController
from slurm_rest.model.dbv0037_cluster_info_associations import Dbv0037ClusterInfoAssociations
from slurm_rest.model.dbv0037_response_tres import Dbv0037ResponseTres
globals()['Dbv0036ClusterInfoController'] = Dbv0036ClusterInfoController
globals()['Dbv0037ClusterInfoAssociations'] = Dbv0037ClusterInfoAssociations
globals()['Dbv0037ResponseTres'] = Dbv0037ResponseTres
from slurm_rest.model.dbv0037_cluster_info import Dbv0037ClusterInfo


class TestDbv0037ClusterInfo(unittest.TestCase):
    """Dbv0037ClusterInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037ClusterInfo(self):
        """Test Dbv0037ClusterInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037ClusterInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
