"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_qos_limits_max_jobs_per import Dbv0036QosLimitsMaxJobsPer
globals()['Dbv0036QosLimitsMaxJobsPer'] = Dbv0036QosLimitsMaxJobsPer
from slurm_rest.model.dbv0036_qos_limits_max_jobs import Dbv0036QosLimitsMaxJobs


class TestDbv0036QosLimitsMaxJobs(unittest.TestCase):
    """Dbv0036QosLimitsMaxJobs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036QosLimitsMaxJobs(self):
        """Test Dbv0036QosLimitsMaxJobs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036QosLimitsMaxJobs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
