"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_qos_limits_max_accruing import Dbv0036QosLimitsMaxAccruing
from slurm_rest.model.dbv0036_qos_limits_max_jobs import Dbv0036QosLimitsMaxJobs
from slurm_rest.model.dbv0036_qos_limits_max_tres import Dbv0036QosLimitsMaxTres
from slurm_rest.model.dbv0036_qos_limits_max_wall_clock import Dbv0036QosLimitsMaxWallClock
globals()['Dbv0036QosLimitsMaxAccruing'] = Dbv0036QosLimitsMaxAccruing
globals()['Dbv0036QosLimitsMaxJobs'] = Dbv0036QosLimitsMaxJobs
globals()['Dbv0036QosLimitsMaxTres'] = Dbv0036QosLimitsMaxTres
globals()['Dbv0036QosLimitsMaxWallClock'] = Dbv0036QosLimitsMaxWallClock
from slurm_rest.model.dbv0036_qos_limits_max import Dbv0036QosLimitsMax


class TestDbv0036QosLimitsMax(unittest.TestCase):
    """Dbv0036QosLimitsMax unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036QosLimitsMax(self):
        """Test Dbv0036QosLimitsMax"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036QosLimitsMax()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
