"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.v0037_error import V0037Error
from slurm_rest.model.v0037_node import V0037Node
globals()['V0037Error'] = V0037Error
globals()['V0037Node'] = V0037Node
from slurm_rest.model.v0037_nodes_response import V0037NodesResponse


class TestV0037NodesResponse(unittest.TestCase):
    """V0037NodesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0037NodesResponse(self):
        """Test V0037NodesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V0037NodesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
