"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_job_step_statistics_cpu import Dbv0036JobStepStatisticsCPU


class TestDbv0036JobStepStatisticsCPU(unittest.TestCase):
    """Dbv0036JobStepStatisticsCPU unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036JobStepStatisticsCPU(self):
        """Test Dbv0036JobStepStatisticsCPU"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036JobStepStatisticsCPU()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
