"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.v0036_error import V0036Error
from slurm_rest.model.v0036_job_response_properties import V0036JobResponseProperties
globals()['V0036Error'] = V0036Error
globals()['V0036JobResponseProperties'] = V0036JobResponseProperties
from slurm_rest.model.v0036_jobs_response import V0036JobsResponse


class TestV0036JobsResponse(unittest.TestCase):
    """V0036JobsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0036JobsResponse(self):
        """Test V0036JobsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V0036JobsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
