"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0037_error import Dbv0037Error
globals()['Dbv0037Error'] = Dbv0037Error
from slurm_rest.model.dbv0037_response_association_delete import Dbv0037ResponseAssociationDelete


class TestDbv0037ResponseAssociationDelete(unittest.TestCase):
    """Dbv0037ResponseAssociationDelete unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037ResponseAssociationDelete(self):
        """Test Dbv0037ResponseAssociationDelete"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037ResponseAssociationDelete()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
