"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_association import Dbv0036Association
from slurm_rest.model.dbv0036_error import Dbv0036Error
globals()['Dbv0036Association'] = Dbv0036Association
globals()['Dbv0036Error'] = Dbv0036Error
from slurm_rest.model.dbv0036_associations_info import Dbv0036AssociationsInfo


class TestDbv0036AssociationsInfo(unittest.TestCase):
    """Dbv0036AssociationsInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036AssociationsInfo(self):
        """Test Dbv0036AssociationsInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036AssociationsInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
