"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_diag_time import Dbv0036DiagTime
globals()['Dbv0036DiagTime'] = Dbv0036DiagTime
from slurm_rest.model.dbv0036_diag_rpcs import Dbv0036DiagRPCs


class TestDbv0036DiagRPCs(unittest.TestCase):
    """Dbv0036DiagRPCs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036DiagRPCs(self):
        """Test Dbv0036DiagRPCs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036DiagRPCs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
