"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_association_max_jobs import Dbv0036AssociationMaxJobs
from slurm_rest.model.dbv0036_association_max_per import Dbv0036AssociationMaxPer
from slurm_rest.model.dbv0037_association_max_tres import Dbv0037AssociationMaxTres
globals()['Dbv0036AssociationMaxJobs'] = Dbv0036AssociationMaxJobs
globals()['Dbv0036AssociationMaxPer'] = Dbv0036AssociationMaxPer
globals()['Dbv0037AssociationMaxTres'] = Dbv0037AssociationMaxTres
from slurm_rest.model.dbv0037_association_max import Dbv0037AssociationMax


class TestDbv0037AssociationMax(unittest.TestCase):
    """Dbv0037AssociationMax unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037AssociationMax(self):
        """Test Dbv0037AssociationMax"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037AssociationMax()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
