"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.v0037_node_allocation import V0037NodeAllocation
globals()['V0037NodeAllocation'] = V0037NodeAllocation
from slurm_rest.model.v0037_job_resources import V0037JobResources


class TestV0037JobResources(unittest.TestCase):
    """V0037JobResources unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0037JobResources(self):
        """Test V0037JobResources"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V0037JobResources()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
