"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_job_time_total import Dbv0036JobTimeTotal


class TestDbv0036JobTimeTotal(unittest.TestCase):
    """Dbv0036JobTimeTotal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036JobTimeTotal(self):
        """Test Dbv0036JobTimeTotal"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036JobTimeTotal()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
