"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_job_step_step_het import Dbv0036JobStepStepHet
from slurm_rest.model.dbv0036_job_step_step_task import Dbv0036JobStepStepTask
from slurm_rest.model.dbv0037_job_step_step_tres import Dbv0037JobStepStepTres
globals()['Dbv0036JobStepStepHet'] = Dbv0036JobStepStepHet
globals()['Dbv0036JobStepStepTask'] = Dbv0036JobStepStepTask
globals()['Dbv0037JobStepStepTres'] = Dbv0037JobStepStepTres
from slurm_rest.model.dbv0037_job_step_step import Dbv0037JobStepStep


class TestDbv0037JobStepStep(unittest.TestCase):
    """Dbv0037JobStepStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037JobStepStep(self):
        """Test Dbv0037JobStepStep"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037JobStepStep()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
