"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0037_qos_limits_max import Dbv0037QosLimitsMax
from slurm_rest.model.dbv0037_qos_limits_min import Dbv0037QosLimitsMin
globals()['Dbv0037QosLimitsMax'] = Dbv0037QosLimitsMax
globals()['Dbv0037QosLimitsMin'] = Dbv0037QosLimitsMin
from slurm_rest.model.dbv0037_qos_limits import Dbv0037QosLimits


class TestDbv0037QosLimits(unittest.TestCase):
    """Dbv0037QosLimits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037QosLimits(self):
        """Test Dbv0037QosLimits"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037QosLimits()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
