"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0037_error import Dbv0037Error
globals()['Dbv0037Error'] = Dbv0037Error
from slurm_rest.model.dbv0037_account_response import Dbv0037AccountResponse


class TestDbv0037AccountResponse(unittest.TestCase):
    """Dbv0037AccountResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037AccountResponse(self):
        """Test Dbv0037AccountResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037AccountResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
