"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_job_step_step_tres_requested import Dbv0036JobStepStepTresRequested
from slurm_rest.model.dbv0036_tres_list import Dbv0036TresList
globals()['Dbv0036JobStepStepTresRequested'] = Dbv0036JobStepStepTresRequested
globals()['Dbv0036TresList'] = Dbv0036TresList
from slurm_rest.model.dbv0036_job_step_step_tres import Dbv0036JobStepStepTres


class TestDbv0036JobStepStepTres(unittest.TestCase):
    """Dbv0036JobStepStepTres unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036JobStepStepTres(self):
        """Test Dbv0036JobStepStepTres"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036JobStepStepTres()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
