"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_association_max_tres_minutes import Dbv0036AssociationMaxTresMinutes
from slurm_rest.model.dbv0036_association_max_tres_per import Dbv0036AssociationMaxTresPer
from slurm_rest.model.dbv0036_tres_list import Dbv0036TresList
globals()['Dbv0036AssociationMaxTresMinutes'] = Dbv0036AssociationMaxTresMinutes
globals()['Dbv0036AssociationMaxTresPer'] = Dbv0036AssociationMaxTresPer
globals()['Dbv0036TresList'] = Dbv0036TresList
from slurm_rest.model.dbv0036_association_max_tres import Dbv0036AssociationMaxTres


class TestDbv0036AssociationMaxTres(unittest.TestCase):
    """Dbv0036AssociationMaxTres unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036AssociationMaxTres(self):
        """Test Dbv0036AssociationMaxTres"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036AssociationMaxTres()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
