"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_association_short_info import Dbv0036AssociationShortInfo
from slurm_rest.model.dbv0036_job_array import Dbv0036JobArray
from slurm_rest.model.dbv0036_job_comment import Dbv0036JobComment
from slurm_rest.model.dbv0036_job_exit_code import Dbv0036JobExitCode
from slurm_rest.model.dbv0036_job_het import Dbv0036JobHet
from slurm_rest.model.dbv0036_job_mcs import Dbv0036JobMcs
from slurm_rest.model.dbv0036_job_required import Dbv0036JobRequired
from slurm_rest.model.dbv0036_job_reservation import Dbv0036JobReservation
from slurm_rest.model.dbv0036_job_state import Dbv0036JobState
from slurm_rest.model.dbv0036_job_step import Dbv0036JobStep
from slurm_rest.model.dbv0036_job_time import Dbv0036JobTime
from slurm_rest.model.dbv0036_job_tres import Dbv0036JobTres
from slurm_rest.model.dbv0036_job_wckey import Dbv0036JobWckey
globals()['Dbv0036AssociationShortInfo'] = Dbv0036AssociationShortInfo
globals()['Dbv0036JobArray'] = Dbv0036JobArray
globals()['Dbv0036JobComment'] = Dbv0036JobComment
globals()['Dbv0036JobExitCode'] = Dbv0036JobExitCode
globals()['Dbv0036JobHet'] = Dbv0036JobHet
globals()['Dbv0036JobMcs'] = Dbv0036JobMcs
globals()['Dbv0036JobRequired'] = Dbv0036JobRequired
globals()['Dbv0036JobReservation'] = Dbv0036JobReservation
globals()['Dbv0036JobState'] = Dbv0036JobState
globals()['Dbv0036JobStep'] = Dbv0036JobStep
globals()['Dbv0036JobTime'] = Dbv0036JobTime
globals()['Dbv0036JobTres'] = Dbv0036JobTres
globals()['Dbv0036JobWckey'] = Dbv0036JobWckey
from slurm_rest.model.dbv0036_job import Dbv0036Job


class TestDbv0036Job(unittest.TestCase):
    """Dbv0036Job unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036Job(self):
        """Test Dbv0036Job"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036Job()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
