"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0037_qos_limits_max_tres_minutes import Dbv0037QosLimitsMaxTresMinutes
from slurm_rest.model.dbv0037_qos_limits_max_tres_per import Dbv0037QosLimitsMaxTresPer
globals()['Dbv0037QosLimitsMaxTresMinutes'] = Dbv0037QosLimitsMaxTresMinutes
globals()['Dbv0037QosLimitsMaxTresPer'] = Dbv0037QosLimitsMaxTresPer
from slurm_rest.model.dbv0037_qos_limits_max_tres import Dbv0037QosLimitsMaxTres


class TestDbv0037QosLimitsMaxTres(unittest.TestCase):
    """Dbv0037QosLimitsMaxTres unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0037QosLimitsMaxTres(self):
        """Test Dbv0037QosLimitsMaxTres"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0037QosLimitsMaxTres()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
