"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import slurm_rest
from slurm_rest.model.dbv0036_user_default import Dbv0036UserDefault


class TestDbv0036UserDefault(unittest.TestCase):
    """Dbv0036UserDefault unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbv0036UserDefault(self):
        """Test Dbv0036UserDefault"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dbv0036UserDefault()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
