"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import slurm_rest
from slurm_rest.api.openapi_api import OpenapiApi  # noqa: E501


class TestOpenapiApi(unittest.TestCase):
    """OpenapiApi unit test stubs"""

    def setUp(self):
        self.api = OpenapiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_openapi_get(self):
        """Test case for openapi_get

        Retrieve OpenAPI Specification  # noqa: E501
        """
        pass

    def test_openapi_json_get(self):
        """Test case for openapi_json_get

        Retrieve OpenAPI Specification  # noqa: E501
        """
        pass

    def test_openapi_v3_get(self):
        """Test case for openapi_v3_get

        Retrieve OpenAPI Specification  # noqa: E501
        """
        pass

    def test_openapi_yaml_get(self):
        """Test case for openapi_yaml_get

        Retrieve OpenAPI Specification  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
