# flake8: noqa

"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


__version__ = "0.0.37.1"

# import ApiClient
from slurm_rest.api_client import ApiClient

# import Configuration
from slurm_rest.configuration import Configuration

# import exceptions
from slurm_rest.exceptions import OpenApiException
from slurm_rest.exceptions import ApiAttributeError
from slurm_rest.exceptions import ApiTypeError
from slurm_rest.exceptions import ApiValueError
from slurm_rest.exceptions import ApiKeyError
from slurm_rest.exceptions import ApiException
