"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from slurm_rest.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from slurm_rest.exceptions import ApiAttributeError



class V0037DiagStatistics(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'parts_packed': (int,),  # noqa: E501
            'req_time': (int,),  # noqa: E501
            'req_time_start': (int,),  # noqa: E501
            'server_thread_count': (int,),  # noqa: E501
            'agent_queue_size': (int,),  # noqa: E501
            'agent_count': (int,),  # noqa: E501
            'agent_thread_count': (int,),  # noqa: E501
            'dbd_agent_queue_size': (int,),  # noqa: E501
            'gettimeofday_latency': (int,),  # noqa: E501
            'schedule_cycle_max': (int,),  # noqa: E501
            'schedule_cycle_last': (int,),  # noqa: E501
            'schedule_cycle_total': (int,),  # noqa: E501
            'schedule_cycle_mean': (int,),  # noqa: E501
            'schedule_cycle_mean_depth': (int,),  # noqa: E501
            'schedule_cycle_per_minute': (int,),  # noqa: E501
            'schedule_queue_length': (int,),  # noqa: E501
            'jobs_submitted': (int,),  # noqa: E501
            'jobs_started': (int,),  # noqa: E501
            'jobs_completed': (int,),  # noqa: E501
            'jobs_canceled': (int,),  # noqa: E501
            'jobs_failed': (int,),  # noqa: E501
            'jobs_pending': (int,),  # noqa: E501
            'jobs_running': (int,),  # noqa: E501
            'job_states_ts': (int,),  # noqa: E501
            'bf_backfilled_jobs': (int,),  # noqa: E501
            'bf_last_backfilled_jobs': (int,),  # noqa: E501
            'bf_backfilled_het_jobs': (int,),  # noqa: E501
            'bf_cycle_counter': (int,),  # noqa: E501
            'bf_cycle_mean': (int,),  # noqa: E501
            'bf_cycle_max': (int,),  # noqa: E501
            'bf_last_depth': (int,),  # noqa: E501
            'bf_last_depth_try': (int,),  # noqa: E501
            'bf_depth_mean': (int,),  # noqa: E501
            'bf_depth_mean_try': (int,),  # noqa: E501
            'bf_cycle_last': (int,),  # noqa: E501
            'bf_queue_len': (int,),  # noqa: E501
            'bf_queue_len_mean': (int,),  # noqa: E501
            'bf_when_last_cycle': (int,),  # noqa: E501
            'bf_active': (bool,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'parts_packed': 'parts_packed',  # noqa: E501
        'req_time': 'req_time',  # noqa: E501
        'req_time_start': 'req_time_start',  # noqa: E501
        'server_thread_count': 'server_thread_count',  # noqa: E501
        'agent_queue_size': 'agent_queue_size',  # noqa: E501
        'agent_count': 'agent_count',  # noqa: E501
        'agent_thread_count': 'agent_thread_count',  # noqa: E501
        'dbd_agent_queue_size': 'dbd_agent_queue_size',  # noqa: E501
        'gettimeofday_latency': 'gettimeofday_latency',  # noqa: E501
        'schedule_cycle_max': 'schedule_cycle_max',  # noqa: E501
        'schedule_cycle_last': 'schedule_cycle_last',  # noqa: E501
        'schedule_cycle_total': 'schedule_cycle_total',  # noqa: E501
        'schedule_cycle_mean': 'schedule_cycle_mean',  # noqa: E501
        'schedule_cycle_mean_depth': 'schedule_cycle_mean_depth',  # noqa: E501
        'schedule_cycle_per_minute': 'schedule_cycle_per_minute',  # noqa: E501
        'schedule_queue_length': 'schedule_queue_length',  # noqa: E501
        'jobs_submitted': 'jobs_submitted',  # noqa: E501
        'jobs_started': 'jobs_started',  # noqa: E501
        'jobs_completed': 'jobs_completed',  # noqa: E501
        'jobs_canceled': 'jobs_canceled',  # noqa: E501
        'jobs_failed': 'jobs_failed',  # noqa: E501
        'jobs_pending': 'jobs_pending',  # noqa: E501
        'jobs_running': 'jobs_running',  # noqa: E501
        'job_states_ts': 'job_states_ts',  # noqa: E501
        'bf_backfilled_jobs': 'bf_backfilled_jobs',  # noqa: E501
        'bf_last_backfilled_jobs': 'bf_last_backfilled_jobs',  # noqa: E501
        'bf_backfilled_het_jobs': 'bf_backfilled_het_jobs',  # noqa: E501
        'bf_cycle_counter': 'bf_cycle_counter',  # noqa: E501
        'bf_cycle_mean': 'bf_cycle_mean',  # noqa: E501
        'bf_cycle_max': 'bf_cycle_max',  # noqa: E501
        'bf_last_depth': 'bf_last_depth',  # noqa: E501
        'bf_last_depth_try': 'bf_last_depth_try',  # noqa: E501
        'bf_depth_mean': 'bf_depth_mean',  # noqa: E501
        'bf_depth_mean_try': 'bf_depth_mean_try',  # noqa: E501
        'bf_cycle_last': 'bf_cycle_last',  # noqa: E501
        'bf_queue_len': 'bf_queue_len',  # noqa: E501
        'bf_queue_len_mean': 'bf_queue_len_mean',  # noqa: E501
        'bf_when_last_cycle': 'bf_when_last_cycle',  # noqa: E501
        'bf_active': 'bf_active',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """V0037DiagStatistics - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            parts_packed (int): partition records packed. [optional]  # noqa: E501
            req_time (int): generation time. [optional]  # noqa: E501
            req_time_start (int): data since. [optional]  # noqa: E501
            server_thread_count (int): Server thread count. [optional]  # noqa: E501
            agent_queue_size (int): Agent queue size. [optional]  # noqa: E501
            agent_count (int): Agent count. [optional]  # noqa: E501
            agent_thread_count (int): Agent thread count. [optional]  # noqa: E501
            dbd_agent_queue_size (int): DBD Agent queue size. [optional]  # noqa: E501
            gettimeofday_latency (int): Latency for 1000 calls to gettimeofday(). [optional]  # noqa: E501
            schedule_cycle_max (int): Main Schedule max cycle. [optional]  # noqa: E501
            schedule_cycle_last (int): Main Schedule last cycle. [optional]  # noqa: E501
            schedule_cycle_total (int): Main Schedule cycle iterations. [optional]  # noqa: E501
            schedule_cycle_mean (int): Average time for Schedule Max cycle. [optional]  # noqa: E501
            schedule_cycle_mean_depth (int): Average depth for Schedule Max cycle. [optional]  # noqa: E501
            schedule_cycle_per_minute (int): Main Schedule Cycles per minute. [optional]  # noqa: E501
            schedule_queue_length (int): Main Schedule Last queue length. [optional]  # noqa: E501
            jobs_submitted (int): Job submitted. [optional]  # noqa: E501
            jobs_started (int): Job started. [optional]  # noqa: E501
            jobs_completed (int): Job completed. [optional]  # noqa: E501
            jobs_canceled (int): Job cancelled. [optional]  # noqa: E501
            jobs_failed (int): Job failed. [optional]  # noqa: E501
            jobs_pending (int): Job pending. [optional]  # noqa: E501
            jobs_running (int): Job running. [optional]  # noqa: E501
            job_states_ts (int): Job states timestamp. [optional]  # noqa: E501
            bf_backfilled_jobs (int): Total backfilled jobs (since last slurm start). [optional]  # noqa: E501
            bf_last_backfilled_jobs (int): Total backfilled jobs (since last stats cycle start). [optional]  # noqa: E501
            bf_backfilled_het_jobs (int): Total backfilled heterogeneous job components. [optional]  # noqa: E501
            bf_cycle_counter (int): Backfill Schedule Total cycles. [optional]  # noqa: E501
            bf_cycle_mean (int): Backfill Schedule Mean cycle. [optional]  # noqa: E501
            bf_cycle_max (int): Backfill Schedule Max cycle time. [optional]  # noqa: E501
            bf_last_depth (int): Backfill Schedule Last depth cycle. [optional]  # noqa: E501
            bf_last_depth_try (int): Backfill Schedule Mean cycle (try sched). [optional]  # noqa: E501
            bf_depth_mean (int): Backfill Schedule Depth Mean. [optional]  # noqa: E501
            bf_depth_mean_try (int): Backfill Schedule Depth Mean (try sched). [optional]  # noqa: E501
            bf_cycle_last (int): Backfill Schedule Last cycle time. [optional]  # noqa: E501
            bf_queue_len (int): Backfill Schedule Last queue length. [optional]  # noqa: E501
            bf_queue_len_mean (int): Backfill Schedule Mean queue length. [optional]  # noqa: E501
            bf_when_last_cycle (int): Last cycle timestamp. [optional]  # noqa: E501
            bf_active (bool): Backfill Schedule currently active. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """V0037DiagStatistics - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            parts_packed (int): partition records packed. [optional]  # noqa: E501
            req_time (int): generation time. [optional]  # noqa: E501
            req_time_start (int): data since. [optional]  # noqa: E501
            server_thread_count (int): Server thread count. [optional]  # noqa: E501
            agent_queue_size (int): Agent queue size. [optional]  # noqa: E501
            agent_count (int): Agent count. [optional]  # noqa: E501
            agent_thread_count (int): Agent thread count. [optional]  # noqa: E501
            dbd_agent_queue_size (int): DBD Agent queue size. [optional]  # noqa: E501
            gettimeofday_latency (int): Latency for 1000 calls to gettimeofday(). [optional]  # noqa: E501
            schedule_cycle_max (int): Main Schedule max cycle. [optional]  # noqa: E501
            schedule_cycle_last (int): Main Schedule last cycle. [optional]  # noqa: E501
            schedule_cycle_total (int): Main Schedule cycle iterations. [optional]  # noqa: E501
            schedule_cycle_mean (int): Average time for Schedule Max cycle. [optional]  # noqa: E501
            schedule_cycle_mean_depth (int): Average depth for Schedule Max cycle. [optional]  # noqa: E501
            schedule_cycle_per_minute (int): Main Schedule Cycles per minute. [optional]  # noqa: E501
            schedule_queue_length (int): Main Schedule Last queue length. [optional]  # noqa: E501
            jobs_submitted (int): Job submitted. [optional]  # noqa: E501
            jobs_started (int): Job started. [optional]  # noqa: E501
            jobs_completed (int): Job completed. [optional]  # noqa: E501
            jobs_canceled (int): Job cancelled. [optional]  # noqa: E501
            jobs_failed (int): Job failed. [optional]  # noqa: E501
            jobs_pending (int): Job pending. [optional]  # noqa: E501
            jobs_running (int): Job running. [optional]  # noqa: E501
            job_states_ts (int): Job states timestamp. [optional]  # noqa: E501
            bf_backfilled_jobs (int): Total backfilled jobs (since last slurm start). [optional]  # noqa: E501
            bf_last_backfilled_jobs (int): Total backfilled jobs (since last stats cycle start). [optional]  # noqa: E501
            bf_backfilled_het_jobs (int): Total backfilled heterogeneous job components. [optional]  # noqa: E501
            bf_cycle_counter (int): Backfill Schedule Total cycles. [optional]  # noqa: E501
            bf_cycle_mean (int): Backfill Schedule Mean cycle. [optional]  # noqa: E501
            bf_cycle_max (int): Backfill Schedule Max cycle time. [optional]  # noqa: E501
            bf_last_depth (int): Backfill Schedule Last depth cycle. [optional]  # noqa: E501
            bf_last_depth_try (int): Backfill Schedule Mean cycle (try sched). [optional]  # noqa: E501
            bf_depth_mean (int): Backfill Schedule Depth Mean. [optional]  # noqa: E501
            bf_depth_mean_try (int): Backfill Schedule Depth Mean (try sched). [optional]  # noqa: E501
            bf_cycle_last (int): Backfill Schedule Last cycle time. [optional]  # noqa: E501
            bf_queue_len (int): Backfill Schedule Last queue length. [optional]  # noqa: E501
            bf_queue_len_mean (int): Backfill Schedule Mean queue length. [optional]  # noqa: E501
            bf_when_last_cycle (int): Last cycle timestamp. [optional]  # noqa: E501
            bf_active (bool): Backfill Schedule currently active. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
